name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '15 3 * * *'

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: [ head, '3.0', '2.7', '2.6', '2.5' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        exclude:
        - { os: windows-latest , ruby: head }
        include:
        - { os: windows-latest , ruby: mingw }
        - { os: windows-latest , ruby: mswin }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Build
      run: rake build
    - name: Run test
      run: rake test
    - name: Installation test
      run: gem install pkg/*.gem
